// src/migration/parity.js
//
// Runtime consumer of the parity report generated by scripts/parity-audit.cjs.
// Fetch once, cache forever (report is a build-time artifact).
//
// Usage:
//   const parity = useParity('panther_buss');
//   // => { status: 'DRIFT', legacyOnly: [...], v1Only: [...] } | null

import { useEffect, useState } from 'react';

let _cache = null;
let _inflight = null;

async function loadReport() {
  if (_cache) return _cache;
  if (_inflight) return _inflight;
  _inflight = fetch('/parity-report.json', { cache: 'no-cache' })
    .then(r => r.ok ? r.json() : null)
    .then(j => { _cache = j; _inflight = null; return j; })
    .catch(() => { _inflight = null; return null; });
  return _inflight;
}

export function useParity(productId) {
  const [entry, setEntry] = useState(() => _cache?.products?.[productId] || null);
  useEffect(() => {
    let alive = true;
    loadReport().then(rep => {
      if (!alive) return;
      setEntry(rep?.products?.[productId] || null);
    });
    return () => { alive = false; };
  }, [productId]);
  return entry;
}
